# Generated by Django 4.2 on 2025-12-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core_features', '0003_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('monday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('monday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('tuesday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('tuesday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('tuesday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('wednesday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('wednesday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('wednesday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('thursday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('thursday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('thursday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('friday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('friday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('friday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('saturday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('saturday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('saturday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday_breakfast', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday_lunch', models.CharField(blank=True, max_length=255, null=True)),
                ('sunday_dinner', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_features.users')),
            ],
        ),
    ]
